version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'bot:dependabot'
    commit-message:
      prefix: 'deps'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'actions'
    commit-message:
      prefix: 'deps'
  # - package-ecosystem: 'docker'
  #   directory: '/'
  #   schedule:
  #     interval: 'monthly'
  #   labels:
  #     - 'dependencies'
