name: Bug Report
description: Report a bug in the repository
title: '[Bug]: '
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.
        Please provide clear and accurate details to help us reproduce and fix the issue faster.

  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots or recordings to help explain the problem.
      placeholder: Drag and drop images here
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Where did you encounter this bug?
      options:
        - Desktop
        - Mobile
        - Both
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: Windows 11 / macOS 14 / Ubuntu 22.04
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: Chrome / Firefox / Safari
    validations:
      required: false

  - type: input
    id: app_version
    attributes:
      label: App / Browser Version
      placeholder: e.g. 120.0.0
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or information about the problem.
      placeholder: Logs, links, or extra details
    validations:
      required: false
