name: Command Request
description: Suggest a new command for the bot
title: "[Command Request]: "
labels:
  - enhancement
  - commands

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new command!
        Please provide as much detail as possible so we can evaluate it properly.

  - type: textarea
    id: command_summary
    attributes:
      label: Command Summary
      description: Briefly summarize the command you are requesting.
      placeholder: Short summary of the command
    validations:
      required: true

  - type: textarea
    id: command_description
    attributes:
      label: Command Description
      description: |
        Provide a detailed description of the command.
        Include:
        - Command syntax and parameters
        - Expected behavior and output
        - Use cases for this command
      placeholder: Describe how the command works
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how the command would be used.
      placeholder: |
        /command argument1 argument2
        /command --option value
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the command request.
      placeholder: Links, screenshots, or extra details
    validations:
      required: false
