name: Feature Request
description: Suggest a new feature for the bot
title: "[Feature Request]: "
labels:
  - enhancement

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly summarize the feature you are requesting.
      placeholder: Short and clear summary of the feature
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Provide a detailed description of the feature.
        Include:
        - What problem does this feature address?
        - How would this feature improve the bot?
        - Any potential implementation ideas.
      placeholder: Explain the feature in detail
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: Explain the potential impact of this feature on the bot and its users.
      placeholder: Describe the impact
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Links, screenshots, or extra details
    validations:
      required: false
